### ISSUE TITLE
dcrd cert file error on launch

### ISSUE THREAD

**Issue by raedah** [decred/dcrticketbuyer#11]
[z@mac decred-v0.1.5]$ ./dcrticketbuyer
Failed to read dcrd cert file at /home/z/.dcrd: read /home/z/.dcrd: is a directory

**Comment by jcvernaleo** [comment]
Are you on the latest master?

It is possible that there is a mac specific bug.  I'll test that once I get my mac to boot up.  For the moment you can specify your cert file location with --dcrdcert=

**Comment by jcvernaleo** [comment]
Okay, I tried and the latest master does the right thing on a mac:
      --dcrdcert=           File containing the dcrd certificate file
                            (/Users/jcv/Library/Application
                            Support/Dcrd/rpc.cert)
@raedah can you try updating?

**Comment by raedah** [comment]
Possibly related to this error, that I get when I manually specify the cert.

[z@mac decred-v0.1.5]$ ./dcrticketbuyer --dcrdcert=/home/z/.dcrd/rpc.cert 
Failed to start dcrd rpcclient: dial tcp 127.0.0.1:19109: getsockopt: connection refused

dcrd is running, and I see 127.0.0.1:9109 listening, which I see is a different port. Not sure what 19109 is suppose to be.

I'll either try to get it built from the the latest master code, or try 0.1.6 if that comes out shortly.

**Comment by raedah** [comment]
Changed to master for dcrd, dcrwallet, and dcrticketbuyer. Now I get different errors.

[z@hostz bin]$ ./dcrticketbuyer
Failed to start dcrd rpcclient: authentication failure

[z@hostz bin]$ ./dcrticketbuyer --dcrdcert=/home/z/.dcrwallet/rpc.cert
Failed to start dcrd rpcclient: x509: certificate signed by unknown authority

**Comment by chappjc** [comment]
@raedah You've specified .dcrwallet/rpc.cert for dcrdcert (not dcrwcert).

Also, the sample config file is misleading. Your error:

```
Failed to read dcrd cert file at /home/z/.dcrd: read /home/z/.dcrd: is a directory
```

Is caused by specifying the directory in the config file instead of the actual rpc.cert.  The sample config is sort of wrong:

```
dcrdcert=path/to/.dcrd
```

Should say:

```
 dcrdcert=path/to/.dcrd/rpc.cert
```
