### ISSUE TITLE
maxinmempool ambiguous

### ISSUE THREAD

**Issue by raedah** [decred/dcrticketbuyer#18]
The description of  maxinmempool  in --help and in the example.conf is ambiguous because it is not clear if it is tracking just your tickets in the mempool or anyones tickets in the mempool. I actually thought it meant all tickets, but after reviewing the debug logs, it appears its only your own tickets.

Related to this is the  dontwaitfortickets  option which says "Don't wait until your last round of tickets have entered the blockchain to attempt to purchase more" but its not clear what a round is. What if only half of your tickets get mined? Will it send more tickets or wait till all of your tickets get mined?

**Comment by alexlyp** [comment]
sorry for the delay on responding to issues here... been busy with getting dcr\* release out.  we will be responding to and cleaning up these for next release.

but yes, maxinmempool refers to how many tickets you currently have waiting to be mined.  So this will limit the ticketbuyer from just piling up tickets which may never get mined.

**Comment by alexlyp** [comment]
we'll add text to make sure that this is clarified
