### ISSUE TITLE
Consolidate webui folder

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrticketbuyer#2]
As @jolan pointed out in #1 there are some ways to include the contents of the webui folder in the binary (and then it could write the files to ~/.dcrticketbuyer/webui/).

Including assets in source code is yucky but so is depending on a folder in a known place.

So we should at least consider this (or if there are other options think about them).

**Comment by davecgh** [comment]
I don't find including the web server assets in the binary bad at all.  In fact, I prefer it.
