### ISSUE TITLE
automatically adjust the value of maxperblock

### ISSUE THREAD

**Issue by raedah** [decred/dcrticketbuyer#22]
If there are 100 blocks remaining in the window, and the buyer is planning to purchase 10 tickets within the current window (or for minpricescale, to the proportional amount of the ideal ticket price), then dcrticketbuyer would buy approximately every 10 blocks. It would recalculate and update the equation after every ticket purchasing so that it adjust as it goes along in order to take account for delays in purchases being mined as well as any change in available spending balance.

Benefits:
-The user wont have to frequently adjust maxperblock by hand to make sure the right number of tickets are purchased. Less manual configuration required.
-Keeps ticket fees more stable since all tickets are not trying to get into the earlier blocks.
-Would help keep the expected estimatestakediff accurate during the window.
-Useful when minpricescale activates. It is better to let others purchase tickets who want to first, rather then raising the price higher then it needs to go if others buy after you. It helps reduce the dilemma of people trying to hold out to see if someone else will raise the price first. A better functioning minpricescale encourges users to keep it enabled. Then the default could also potentialy be set higher to 0.95 instead of 0.7, helping to stabilize the price.

**Comment by raedah** [comment]
Another issue this will fix is that currently when the buyer doesnt spread the buys throughout the window, there is a lot of competition to get in the early blocks of the window, which drives the fees on those purchases way up, costing the user substantially.

**Comment by cjepson** [comment]
I am not sure there is an easy solution to this, because it relies on knowing what other users in the network will try to do. The current program attempts to be as greedy as possible with ticket purchases, and it's impossible to know how many other users will buy tickets in this window and whether or not it is ideal to wait. The program could try to estimate demand, but that might open the user up to abuse based around that algorithm.

**Comment by marcopeereboom** [comment]
Closing this since there is no clear solution.

**Comment by raedah** [comment]
The current solution is actually not as greedy as possible. It is just a static number setting, default maxperblock=5, that may be more or less greedy for different users. The current static solution is already abuse causing fee costs to rise higher due to an early flood of purchases. (5 is aggressive for the average user.) Yes, there is no perfect way to adjust maxperblock since future behavior of other users is not knowable. Short of perfect, I believe we can improve upon this static default. 

Having a maxperblock=evenly which spreads purchases evenly through the window offers many of the benefits I mentioned above. As for the abuse of this, it has not been clearly defined here. The scenarios I have looked at are not compelling. This feature would be an improvement. It could also be done as a percentage of the window, so maxperblock=100% to purchase evenly throughout the remaining window, or maxperblock=70% to aim to purchase all tickets within the first 70% of the remaining window to be more aggressive. This would allow a greedier setting while still taking into account the number of ticket purchases planned for the users available funds.
