### ISSUE TITLE
paying higher fees even when blocks are not full

### ISSUE THREAD

**Issue by raedah** [decred/dcrticketbuyer#23]
Dcrticketbuyer uses the mean/median ticket fee for the last x blocks to set the ticket fee value you will be paying. This ends up in a situation where everyone continues paying a progressively higher ticket fee during a window, even when less then 20 tickets are being purchased per block. The desired behavior is to calculate what fee needs to be paid to get into a block and minimize costs.

**Comment by cjepson** [comment]
Check the code. For new difficulty periods, it actually searches for the average price paid in previous windows with a similar price rather than using the previous blocks.

**Comment by raedah** [comment]
Average price paid is inconsequential here. If blocks have less then 20 purchases, the buyer only needs to pay the minimum fee of 0.01.

**Comment by raedah** [comment]
related to #31

**Comment by raedah** [comment]
[INF] DCRD: Block height 66646 connected

[DBG] TKBY: Mean fee for the last blocks or window period was 0.4399145545454546; this was scaled to 0.05

Almost none of the blocks previous were full (of fresh stake), nor were any of the purchases paying that high of a fee, so I dont know why it thinks the mean fee should be nearly half a decred. blockstoavg is at default 11. Even if logical somehow (which I dont see), still, blocks are not even full of stake.
