### ISSUE TITLE
avgpricemode dual is far off

### ISSUE THREAD

**Issue by raedah** [decred/dcrticketbuyer#28]
These are the numbers being reported for the target price. Dual is far off from what is expected.

avgpricemode=vwap  24.97240151
avgpricemode=pool  24.97060493
avgpricemode=dual  11.31349543

**Comment by cjepson** [comment]
This is strange. Your pool mode is returning the same as VWAP approximately.

It looks like dual mode is returning half the price in the ticket pool, so during the calculation the VWAP must be set to zero. Will look into it.

**Comment by alexlyp** [comment]
Fixed in #46
