### ISSUE TITLE
Problem buying tickets

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrticketbuyer#38]
My testnet dcrticketbuyer bought maybe 2 dozen tickets just fine and then stopped with errors about expiry showing up on each block:

```
11:18:41 2016-08-19 [INF] TKBY: Purchased ticket 84af33691ed150074759a9c6c42a698c6ade1ac2cd1fe0656b56541916fe1272 at stake difficulty 17.03362513 (0.01 fees per KB used)
11:19:13 2016-08-19 [INF] DCRD: Block height 144047 connected
11:26:59 2016-08-19 [INF] DCRD: Block height 144048 connected
11:33:38 2016-08-19 [ERR] TKBY: Failed to purchase tickets this round: -4: need expiry that is beyond next height (given: 144064, next height 144064)
```

I've restarted dcrticketbuyer and will see if it starts buying again.

**Comment by jcvernaleo** [comment]
Confirmed that after restart it starts buying tickets again.

**Comment by jcvernaleo** [comment]
With the latest code (and a fresh wallet regenerated from seed as my old wallet db finally got too messed up after multiple unclean shutdowns due to hardware issues) dcrticketbuyer no longer gets stuck like this.  It will still occasionally hit that error for one ticket but then resumes buying normally without any intervention.

I'm still investigating why it hits the error sometimes but it is not nearly as bad as it was before.

**Comment by jcvernaleo** [comment]
I have been trying for over a week to reproduce the issue again and have not seen it (and I was the only one who saw it in the first place).  It appears that some of the newer code (wallet and daemon) has made this issue go away.  Since I only saw it on my slowest machine I believe it was performance related (and much of that has improved).  So I'm closing this issue and it can be reopened if we ever hit this again.

**Comment by raedah** [comment]
Sounds like this, which was fixed. https://github.com/decred/dcrticketbuyer/issues/52
