### ISSUE TITLE
Tickets not being bought

### ISSUE THREAD

**Issue by raedah** [decred/dcrticketbuyer#52]
I set highpricepenalty=1.0 (default is 1.3) so that there would be no penalty and tickets would continue being purchased to use up all my funds. balancetomaintain is set to 0.0 and maxpricescale is set to 10.0 so that again, nothing would stand in the way of buying tickets and using all my available funds. maxpriceabsolute was set well above the current price. I have enough funds for many buys remaining. debuglevel is set to trace and I see "[TRC] TKBY: All tickets have been purchased, aborting further ticket purchases".  The 12 hour window passes and my funds are not spent.

**Comment by raedah** [comment]
My only guess is that maybe this is caused by #21

**Comment by alexlyp** [comment]
I have just observed something similar to this on testnet, appears to be an issue with a calculation on stakediff retarget blocks.  Should have a fix out shortly.
