### ISSUE TITLE
maxinmempool defaults to 0 instead of 40

### ISSUE THREAD

**Issue by raedah** [decred/dcrticketbuyer#60]
https://github.com/decred/dcrticketbuyer/blob/master/config.go#L68

https://github.com/decred/dcrticketbuyer/blob/master/ticketbuyer-example.conf#L55

**Comment by jolan** [comment]
There are other options where the default doesn't match the commented out example in the sample config (like maxperblock).  Might as well fix them all.

**Comment by raedah** [comment]
@jolan such as?

**Comment by raedah** [comment]
@jolan 
defaultMaxPerBlock        = 3
maxperblock=3

looks the same to me.

**Comment by raedah** [comment]
This was fixed in https://github.com/decred/dcrwallet/pull/374
