### ISSUE TITLE
Update to use latest dcrwallet

### ISSUE THREAD

**Issue by tuxcanfly** [decred/dcrticketbuyer#82]
pkg `ticketbuyer` is now part of `dcrwallet` which uses it to make automatic ticket purchases. 

`dcrticketbuyer` should be updated to make use of the pkg via RPCs  to make configuration changes and toggle purchasing.

**Comment by raedah** [comment]
All the logic was moved to dcrwallet, which was pretty much all that was good. I dont see why dcrticketbuyer would stick around at all when the user can just control dcrwallet with the RPCs.

**Comment by raedah** [comment]
this repo is being depreciated, so this one can be closed
