### ISSUE TITLE
Tickets remaining to be purchased in window should reflect possible tickets left in the window.

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrticketbuyer#9]
16:40:14 2016-06-03 [DBG] TKBY: Tickets remaining to be purchased in this window: 96622

This is far above any possible amount of tickets that a window could include.

So at the most it should be 2880 (144 \* 20) then go down from there

**Comment by raedah** [comment]
When the ticker buyer is first launched, its usually in the middle of a window, so in that case the max would be far less then 2880.

**Comment by raedah** [comment]
buy this window was scaled from 12 to -9223372036854775808

**Comment by raedah** [comment]
Another glitchy thing here is when "Attempting to manipulate the stake difficulty so that the price does not fall below the set minimum", tickets remaining becomes negative. "Tickets remaining to be purchased in this window: -6"
